### ISSUE TITLE
Support updateCard for expiry only

### ISSUE THREAD

**Issue by davecoates** [thephpleague/omnipay-stripe#8] opened 2014-10-06 08:20 UTC
It would be nice to be able to update just the card expiry date rather than only supporting full credit card details. Stripe supports this:

https://stripe.com/docs/api#update_card

I'd be happy to send a pull request but would like to clarify the best way to implement it. Should it be a new message request type (eg. UpdateCardExpiryRequest) and switch the request used in updateCard() based on the presence of the card id parameter (eg. card_id)?

**Comment by delatbabel** [comment] 2015-02-13 04:42
I've just noticed this myself while updating the API documentation. The fundamental problem is that the createCard request that we have isn't actually a createCard, it's a createCustomer.  We need to implement createCard separately. The problem is that the Stripe gateway requires you to have a valid customer ID before you can create a card ID, unlike most other gateways. I'll have a think about how we do this within the OmniPay paradigm.

Is the OP still intending to put forwards a PR or should I pick this up?

**Comment by kayladnls** [comment] 2015-02-13 16:07
@davecoates Are you still planning to PR, or can @delatbabel take that up?

**Comment by davecoates** [comment] 2015-02-13 22:10
@kayladnls my apologies - this requirement was dropped from my project and I forgot to come back to this. @delatbabel if you could take it up that would be great

**Comment by delatbabel** [comment] 2015-02-16 06:17
This should be fixed in Issue #13

**Closed** 2016-03-15 03:55 UTC
